/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_m2mi_speck_jni_SpeckTesterJNI */

#ifndef _Included_com_m2mi_speck_jni_SpeckTesterJNI
#define _Included_com_m2mi_speck_jni_SpeckTesterJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_m2mi_speck_jni_SpeckTesterJNI
 * Method:    testCBCEncryptionSpeed
 * Signature: (III)I
 */
JNIEXPORT jlongArray JNICALL Java_com_m2mi_speck_jni_SpeckTesterJNI_testCBCSpeed
  (JNIEnv *, jobject, jint, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
